spring:
  application:
    name: api-gateway
server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
      # 可传递cookie
      sensitiveHeader: ""
    api-b:
          path: /api-b/**
          serviceId: feign-consumer
          # 可传递cookie
          customSensitiveHeaders: true
  # 网关在进行路由转发前为请求设置Host，以标识最初的服务端请求地址。（解决重定向问题）
  add-host-header: true
ribbon:
  # 设置路由转发请求的时候 ，创建请求链接的超时时间
  ReadTimeout: 60000
  # 设置路由转发请求的超时时间
  ConnectTimeout: 60000
