eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/,http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
server:
  #当前服务端口号
  port: 8765
spring:
  application:
    #当前应用名称
    name: ribbon-consumer