eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
    # Eureka客户端健康监测交由spring-boot-actuator模块的/health端点
    healthcheck:
      enabled: true
server:
  port: 8765
spring:
  application:
    name: ribbon-consumer