spring:
  application:
    name: turbine
server:
  port: 8767
management:
  port: 8768
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://eureka1:1111/eureka/,http://eureka2:1112/eureka/
