spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qianli851205/SpringcloudDemo.git
          search-paths: config-repo
          username: qianli851205
          password: 123hudiefei
      label: config
  rabbitmq:
    port: 5672
    host: localhost
    username: springcloud
    password: 123456
server:
  port: 9000
#security:
#  user:
#    name: user
#    password: 37cc5635-559b-4e6f-b633-7e932b813f73
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://eureka1:1111/eureka/,http://eureka2:1112/eureka/